<?xml version="1.0"?>

<!--
	definitions of some macros for easier description of the robot
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  
          ixx="${m*(3*r*r+h*h)/12}" 
    			ixy = "0" 
    			ixz = "0"
    			iyy="${m*(3*r*r+h*h)/12}" 
    			iyz = "0"
    			izz="${m*r*r/2}"
    />
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia  
          ixx="${m*(y*y+z*z)/12}" 
    			ixy = "0" 
    			ixz = "0"
    			iyy="${m*(x*x+z*z)/12}" 
    			iyz = "0"
    			izz="${m*(x*x+z*z)/12}"
    />
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertia  
          ixx="${2*m*r*r/5}" 
    			ixy = "0" 
    			ixz = "0"
    			iyy="${2*m*r*r/5}" 
    			iyz = "0"
    			izz="${2*m*r*r/5}"
    />
  </xacro:macro>

  <xacro:macro name="wheel" params="lr tY parent">
    <link name="${lr}_wheel">
      <collision>
        <origin xyz="0 0 0" 
        		rpy="${-tY*PI/2} 0 0" />
        <geometry>
          <cylinder 
            length="${wheelWidth}" 
            radius="${wheelRadius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" 
        		rpy="${-tY*PI/2} 0 0" />
        <geometry>
          <mesh filename="package://bbblue_bot_description/meshes/${lr}_wheel.dae" />
        </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" 
        		rpy="${-tY*PI/2} 0 0" />
        <mass value="${wheelMass}"/>
        <cylinder_inertia 
          m="${wheelMass}" 
          r="${wheelRadius}" 
          h="${wheelWidth}"/>
      </inertial>
    </link>

    <gazebo reference="${lr}_wheel">
      <mu1 value="10.0"/>
      <mu2 value="10.0"/>
      <kp  value="10000000.0" />
      <kd>100.0</kd>
      <minDepth>0.00</minDepth>
      <maxVel>1.0</maxVel>   

      <!-- kp>1000000.0</kp>
      <kd>100.0</kd>
      <mu1>200.0</mu1>
      <mu2>100.0</mu2>
      <fdir1>1 0 0</fdir1>
      <maxVel>1.0</maxVel>
      <minDepth>0.00</minDepth>
      <implicitSpringDamper>1</implicitSpringDamper -->

      <material>Gazebo/FlatBlack</material>
    </gazebo>

    <joint name="${lr}_wheel_hinge" type="continuous">
      <parent link="${parent}"/>
      <child link="${lr}_wheel"/>
      <origin 
        xyz = "${wheelOffsetX} ${-tY*(wheelOffsetY+wheelWidth)} -${casterRadius - 0.008}" 
        rpy = "0 0 0" /> 
      <axis xyz="0 1 0" 
      		  rpy="0 0 0" />
      <!--limit effort="100" velocity="10"/-->
      <limit effort="100" velocity="10"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <transmission name="${lr}_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_wheel_hinge">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <!-- hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface -->
      </joint>
      <actuator name="${lr}_joint_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <!-- hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface -->
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  </xacro:macro>

</robot>